#FROM nginx:latest
#COPY ./kk_etcd_ui/build/web /usr/share/nginx/html/web
#COPY ./kk_etcd_ui/lib/docker/default.conf /etc/nginx/conf.d/default.conf
#EXPOSE 80

FROM jitesoft/lighttpd:latest
COPY ./kk_etcd_ui/build/web /var/www/html
EXPOSE 80

# 本地构建测试
# docker build -t kk_etcd_ui_local -f Dockerfile-ui .
# docker run --name kk_etcd_ui_local -p 2334:80  kk_etcd_ui_local


# 多平台构建-发布
# docker login
# docker buildx build --platform linux/amd64,linux/arm64 -t cruvie/kk_etcd_ui:1.4.0 -f Dockerfile-ui . --push


# 测试
# docker pull cruvie/kk_etcd_ui:1.4.0
# docker run --name kk_etcd_ui -p 2334:80 cruvie/kk_etcd_ui:1.4.0

